# Generated by Django 3.1.7 on 2024-01-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='comanda.Produto'),
        ),
    ]
