# Generated by Django 3.1.7 on 2024-01-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0003_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagamento',
            field=models.BooleanField(default=False),
        ),
    ]
