# Generated by Django 3.1.7 on 2024-01-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0004_pedido_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pagamento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='comanda_paga',
            field=models.BooleanField(default=False),
        ),
    ]
